# Generated by Django 4.2.6 on 2024-02-03 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='datePosted',
        ),
    ]
