# Generated by Django 4.2.6 on 2024-02-04 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_dateposted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='startingBid',
            new_name='currentPrice',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='currentBid',
        ),
    ]
